services:
  - type: web
    name: container-mod-system
    env: python
    buildCommands:
      - apt-get update
      - apt-get install -y wkhtmltopdf xvfb
      - pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
    disk:
      name: orders
      mountPath: /opt/render/project/src/orders
      sizeGB: 1